<template>
  <!--
    Three filters, one pane of glass.

    All are reached through `backdrop-filter`/`filter: url(...)`, which is the
    only way to touch live DOM behind an element — a canvas shader cannot see
    what is behind it without re-rendering the page into itself first.

    #crt-warp and #crt-grille share a deliberately lopsided turbulence: very
    low frequency across X, high down Y, so it bands horizontally and the
    displacement moves the image ALONG the scanlines. They are split so the
    backdrop can take the full pull while the phosphor lines only shiver — a
    working tube does not tear its own raster. Same durations, same value
    walk, different scale, so they stay in step.

    #glass-refract is the slab itself: it leaves the middle of the pane alone
    and bends the backdrop inward only within a narrow band at each edge, so
    the CRT warp still owns everything across the centre.
  -->
  <svg class="pointer-events-none absolute h-0 w-0" aria-hidden="true" focusable="false">
    <defs>
      <!-- The backdrop: the picture behind the glass. Full displacement. -->
      <filter id="crt-warp" x="-15%" y="-15%" width="130%" height="130%" color-interpolation-filters="sRGB">
        <feTurbulence
          type="fractalNoise"
          base-frequency="0.0014 0.34"
          num-octaves="1"
          seed="11"
          result="bands"
        >
          <animate
            attributeName="baseFrequency"
            dur="11s"
            values="0.0014 0.34; 0.0031 0.26; 0.0009 0.41; 0.0014 0.34"
            repeatCount="indefinite"
          />
          <animate attributeName="seed" dur="7s" values="11; 14; 9; 11" repeatCount="indefinite" />
        </feTurbulence>

        <!-- R drives the horizontal smear. B is near-flat in fractal noise, so
             using it for Y keeps vertical drift to a shiver, not a wobble. -->
        <feDisplacementMap
          in="SourceGraphic"
          in2="bands"
          scale="14"
          x-channel-selector="R"
          y-channel-selector="B"
        >
          <animate attributeName="scale" dur="5.5s" values="14; 20; 11; 14" repeatCount="indefinite" />
        </feDisplacementMap>
      </filter>

      <!-- The grille: same bands, same clock, a fraction of the pull. -->
      <filter id="crt-grille" x="-15%" y="-15%" width="130%" height="130%" color-interpolation-filters="sRGB">
        <feTurbulence
          type="fractalNoise"
          base-frequency="0.0014 0.34"
          num-octaves="1"
          seed="11"
          result="bands"
        >
          <animate
            attributeName="baseFrequency"
            dur="11s"
            values="0.0014 0.34; 0.0031 0.26; 0.0009 0.41; 0.0014 0.34"
            repeatCount="indefinite"
          />
          <animate attributeName="seed" dur="7s" values="11; 14; 9; 11" repeatCount="indefinite" />
        </feTurbulence>

        <feDisplacementMap
          in="SourceGraphic"
          in2="bands"
          scale="1.6"
          x-channel-selector="R"
          y-channel-selector="B"
        >
          <animate attributeName="scale" dur="5.5s" values="1.6; 2.4; 1.1; 1.6" repeatCount="indefinite" />
        </feDisplacementMap>
      </filter>

      <!-- The slab's edges. /bg/bevel-map.png is a displacement map, not a
           picture: red carries horizontal shift, green vertical, and both sit
           at a neutral 128 through the middle and roll off to the extremes in
           a 14px band at each side. So the backdrop is undisturbed across the
           pane and bends inward sharply near every edge — which is what a
           thick piece of ground glass does to whatever is behind it.

           The roll-off is cosine-eased rather than linear, so the bevel reads
           as a rounded edge instead of a crease. It is generated by
           scripts/build-bevel-map.mjs; the numbers are easier to author as
           pixels than as gradient stops. -->
      <filter
        id="glass-refract"
        filterUnits="objectBoundingBox"
        x="0%"
        y="0%"
        width="100%"
        height="100%"
        color-interpolation-filters="sRGB"
      >
        <!-- No x/y/width/height on the feImage. `primitiveUnits` defaults to
             userSpaceOnUse, so a percentage subregion resolves against the
             VIEWPORT — and this SVG is deliberately 0x0, which made the
             subregion degenerate and left the map unstretched. With no
             subregion the image fills the filter region instead, and the
             region is pinned to the element's own box, so the map's edge
             bands land exactly on the pane's edges. -->
        <feImage href="/bg/bevel-map.png" result="bevel" preserveAspectRatio="none" />
        <feDisplacementMap
          in="SourceGraphic"
          in2="bevel"
          scale="26"
          x-channel-selector="R"
          y-channel-selector="G"
        >
          <animate attributeName="scale" dur="13s" values="26; 31; 23; 26" repeatCount="indefinite" />
        </feDisplacementMap>
      </filter>

    </defs>
  </svg>
</template>
